name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - user/deploy  # main 브랜치에 푸시할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 소스 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # 2. pnpm 캐시 복원
      - name: Restore pnpm cache
        id: cache-pnpm-restore
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}


      # 3. pnpm 설치
      - name: Setup pnpm
        run: |
          npm install -g pnpm@9.15.2
          pnpm config set store-dir ~/.pnpm-store
          
      # 4. 의존성 설치
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Save pnpm cache
        id: cache-pnpm-save
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      # 5. .env 파일 생성
      - name: Create .env file
        run: |
          echo "USER_DATABASE_URL=${{ secrets.USER_DATABASE_URL }}" >> .env
          echo "USER_PULSE_API_KEY=${{ secrets.USER_PULSE_API_KEY }}" >> .env
        shell: bash
        
      # 6. 프리 빌드
      - name: prebuild project
        run: pnpm prebuild  # Pages에 배포할 정적 파일 생성

      # 7. 빌드
      - name: build project
        run: NODE_ENV=production pnpm -filter user pages:build  # Pages에 배포할 정적 파일 생성
        
      # # 8. wrangler 설치치
      # - name: add wrangler
      #   run: pnpm add wrangler@latest -w
        
      # 9. cloudflare pages에 배포
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: "pnpm" # change npm to yarn or pnpm
          environment: production
          # secrets: |
          #   NODE_ENV
          #   USER_DATABASE_URL
          #   USER_PULSE_API_KEY
          workingDirectory: ./apps/user/  # 빌드된 정적 파일이 저장된 디렉토리
          command: pages deploy
        # env:
          # NODE_ENV: production
          # USER_DATABASE_URL: ${{ secrets.USER_DATABASE_URL }}
          # USER_PULSE_API_KEY: ${{ secrets.USER_PULSE_API_KEY }}